heroku_develop:
  image: ruby:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEVELOP --api-key=$HEROKU_API_KEY_DEVELOP
  only:
    - develop

heroku_production:
  image: ruby:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PRODUCTION --api-key=$HEROKU_API_KEY_PRODUCTION
  only:
    - production
